language: python

python:
    - "2.7"

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
    - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
    - conda install --yes -n condaenv pip
    - source activate condaenv
    - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib nose pytest flake8 sphinx lxml sqlalchemy mock future
    - conda install --yes -c obspy obspy
    - pip install --user -r requirements.txt
    - pip install coverage
    - pip install coveralls

install: 
    - pip install --no-deps -v -e .

script: 
    - coverage run --source=pytomo3d setup.py test
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then cd $TRAVIS_BUILD_DIR/doc; make html ; fi

after_success:
    - cd $TRAVIS_BUILD_DIR; coveralls
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then bash $TRAVIS_BUILD_DIR/.travis-update-gh-pages.sh ; f
